# .github/workflows/build-openmohaa.yml
name: Build OpenMOHAA

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build OpenMOHAA for amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            clang \
            lld \
            flex \
            bison \
            libsdl2-dev \
            libopenal-dev \
            libcurl4-openssl-dev

      - name: Configure with CMake
        run: |
          mkdir .cmake
          cd .cmake
          cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./install

      - name: Build project
        run: |
          cd .cmake
          cmake --build . --parallel

      - name: Install project
        run: |
          cd .cmake
          cmake --install .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: openmohaa-amd64
          path: .cmake/install/
