# .github/workflows/build-hl-bots.yml

name: Build HLSDK Bot10

# 🔒 Required for publishing releases
permissions:
  contents: write

on:
  push:
    branches: [ main, master ]
    paths:
      - ".github/workflows/build-hl-bots.yml"
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git
    
    - name: Clone HLSDK Portable (bot10 branch)
      run: |
        git clone --depth 1 --branch bot10 https://github.com/FWGS/hlsdk-portable.git
    
    - name: Build HLSDK Bot10 (AMD64)
      run: |
        cd hlsdk-portable
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DGOLDSOURCE_SUPPORT=ON -D64BIT=ON -Wno-dev
        make -j$(nproc)
        
        # Verify the bot library was built
        ls -la dlls/bot_amd64.so
        file dlls/bot_amd64.so
        
        # Copy to artifacts (rename to standard hl.so name)
        mkdir -p ../../artifacts
        cp dlls/bot_amd64.so ../../artifacts/hl_amd64.so
    
    - name: Upload AMD64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: hl-bot-amd64
        path: artifacts/hl_amd64.so

  build-arm64:
    runs-on: ubuntu-latest
    steps:
    - name: Install cross-compilation tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
    
    - name: Clone HLSDK Portable (bot10 branch)
      run: |
        git clone --depth 1 --branch bot10 https://github.com/FWGS/hlsdk-portable.git
    
    - name: Build HLSDK Bot10 (ARM64)
      run: |
        cd hlsdk-portable
        mkdir build && cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DGOLDSOURCE_SUPPORT=ON \
          -D64BIT=ON \
          -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
          -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
          -DCMAKE_SYSTEM_NAME=Linux \
          -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
          -Wno-dev
        make -j$(nproc)
        
        # The ARM64 build will create bot_arm64.so
        ls -la dlls/bot_*.so
        file dlls/bot_*.so
        
        # Copy to artifacts (rename to standard hl.so name)
        mkdir -p ../../artifacts
        cp dlls/bot_*.so ../../artifacts/hl_arm64.so
    
    - name: Upload ARM64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: hl-bot-arm64
        path: artifacts/hl_arm64.so

  combine-artifacts:
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
    
    - name: Verify bot libraries
      run: |
        echo "=== Built Bot Libraries ==="
        ls -la hl_*.so
        echo ""
        echo "=== File Information ==="
        for f in hl_*.so; do
          echo "File: $f"
          file "$f"
          echo "Size: $(stat -c%s "$f") bytes"
          echo ""
        done
    
    - name: Create release package
      run: |
        mkdir -p release
        cp hl_amd64.so release/hl.so.amd64
        cp hl_arm64.so release/hl.so.arm64
        
        # Also keep the arch-specific names
        cp hl_amd64.so release/
        cp hl_arm64.so release/
        
        # Create usage instructions
        cat > release/README.md << 'EOF'
        # Half-Life Bot Libraries (HLSDK-Portable bot10 branch)
        
        Built from FWGS/hlsdk-portable bot10 branch with bot AI support.
        
        ## Files:
        - `hl_amd64.so` / `hl.so.amd64` - AMD64/x86_64 bot library
        - `hl_arm64.so` / `hl.so.arm64` - ARM64/AArch64 bot library
        
        ## Usage with Xash3D FWGS:
        1. Copy the appropriate library to your Half-Life mod directory
        2. Rename it to `hl.so` 
        3. Use with xash3d-fwgs engine
        
        ## Bot Commands:
        - `bot_add` - Add a bot to the game
        - `bot_kick` - Remove bots
        - Use console commands to control bot behavior
        
        Built: $(date)
        EOF
        
        tar -czf hl-bots-complete.tar.gz -C release .
    
    - name: Upload complete package
      uses: actions/upload-artifact@v4
      with:
        name: hl-bots-complete
        path: |
          hl-bots-complete.tar.gz
          release/
        retention-days: 30
    
    - name: Create release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: hl-bots-complete.tar.gz
        name: "HLSDK Bot Libraries ${{ github.ref_name }}"
        body: |
          Half-Life bot libraries built from HLSDK-Portable bot10 branch.
          
          **Files included:**
          - `hl_amd64.so` - AMD64/x86_64 bot library  
          - `hl_arm64.so` - ARM64/AArch64 bot library
          
          **Usage:** Rename the appropriate file to `hl.so` and place in your Half-Life mod directory.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
