name: Build & Package OpenMoHAA

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            pkg-config \
            libsdl2-dev \
            libopenal-dev \
            libogg-dev \
            libvorbis-dev \
            libjpeg-dev \
            zlib1g-dev

      - name: Configure & compile
        working-directory: ${{ github.workspace }}
        run: |
          echo "Workspace root: $GITHUB_WORKSPACE"
          # Remove any stale build folder to avoid nested directories
          rm -rf build
          mkdir build
          cd build
          # Point CMake at the repo root where CMakeLists.txt lives
          cmake "$GITHUB_WORKSPACE"
          make -j$(nproc)

      - name: Assemble dist folder
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p dist
          cd build
          cp cgame.x86_64.so ../dist/
          cp game.x86_64.so  ../dist/
          cp launch_openmohaa_base.x86_64       ../dist/
          cp launch_openmohaa_breakthrough.x86_64 ../dist/
          cp launch_openmohaa_spearhead.x86_64  ../dist/
          # These may not exist if libs are system-installed; ignore errors
          cp libopenal.so.1   ../dist/ || true
          cp libSDL2-2.0.so.0 ../dist/ || true
          cp omohaaded.x86_64 ../dist/
          cp openmohaa.x86_64 ../dist/

      - name: Upload full package artifact
        uses: actions/upload-artifact@v4
        with:
          name: openmohaa-full-package
          path: dist/
