name: Build Xash3D FWGS Bots

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-xash3d-fwgs-bots.yml'
    branches:
      - main

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: FWGS/hlsdk-portable
          ref: bot10
          submodules: recursive

      - run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential zip libsdl2-dev

      - run: |
          cmake -DENABLE_BOTS=ON -D64BIT=1 -DCMAKE_BUILD_TYPE=Release \
                -B build-amd64 -S .
          cmake --build build-amd64 -- -j$(nproc)

      - run: |
          zip -j bots-amd64.zip build-amd64/dlls/*.so || true
          zip -j bots-amd64.zip build-amd64/cl_dll/*.so || true

      - uses: actions/upload-artifact@v4
        with:
          name: bots-amd64.zip
          path: bots-amd64.zip

  build-i386:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: FWGS/hlsdk-portable
          ref: bot10
          submodules: recursive

      - run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y cmake build-essential gcc-multilib g++-multilib zip \
            libsdl2-2.0-0:i386

      - run: |
          cmake -DENABLE_BOTS=ON -D64BIT=0 -DCMAKE_BUILD_TYPE=Release \
                -B build-i386 -S .
          cmake --build build-i386 -- -j$(nproc)

      - run: |
          zip -j bots-i386.zip build-i386/dlls/*.so || true
          zip -j bots-i386.zip build-i386/cl_dll/*.so || true

      - uses: actions/upload-artifact@v4
        with:
          name: bots-i386.zip
          path: bots-i386.zip

  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: FWGS/hlsdk-portable
          ref: bot10
          submodules: recursive

      - run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential zip \
            gcc-12-aarch64-linux-gnu g++-12-aarch64-linux-gnu libsdl2-dev

      - run: |
          cmake -DENABLE_BOTS=ON -D64BIT=1 -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc-12 \
                -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++-12 \
                -B build-arm64 -S .
          cmake --build build-arm64 -- -j$(nproc)

      - run: |
          zip -j bots-arm64.zip build-arm64/dlls/*.so || true
          zip -j bots-arm64.zip build-arm64/cl_dll/*.so || true

      - uses: actions/upload-artifact@v4
        with:
          name: bots-arm64.zip
          path: bots-arm64.zip

  release:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-i386, build-arm64]
    steps:
      - uses: actions/download-artifact@v4
        with: { name: bots-amd64.zip, path: . }
      - uses: actions/download-artifact@v4
        with: { name: bots-i386.zip, path: . }
      - uses: actions/download-artifact@v4
        with: { name: bots-arm64.zip, path: . }

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: xash3d-fwgs-bots
          name: Xash3D FWGS Bots
          files: |
            bots-amd64.zip
            bots-i386.zip
            bots-arm64.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
