name: Build Xash3D FWGS Bots

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/build-xash3d-fwgs-bots.yml'
    branches:
      - main

jobs:
  build-and-release:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '') || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout bot10 branch
      uses: actions/checkout@v3
      with:
        repository: FWGS/hlsdk-portable
        ref: bot10
        submodules: recursive

    - name: Install build dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y cmake build-essential gcc-multilib g++-multilib libsdl2-dev libsdl2-dev:i386

    - name: Configure with CMake (64-bit)
      run: |
        cmake -D64BIT=1 -DCMAKE_BUILD_TYPE=Release -B build -S .

    - name: Build bot.so / hl.so
      run: |
        cmake --build build -- -j$(nproc)

    - name: Collect artifacts
      run: |
        mkdir -p release
        cp build/dlls/*.so release/ || true
        cp build/cl_dll/*.so release/ || true

    - name: Set dynamic tag
      run: echo "RELEASE_TAG=xash3d-fwgs-bots-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        name: Xash3D FWGS Bots
        files: release/*.so
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
