# .github/workflows/build-openmohaa.yml
name: Build OpenMOHAA

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build for AMD64

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake libsdl2-dev libglew-dev libopenal-dev libvorbis-dev

      - name: Configure project
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build OpenMOHAA
        run: |
          cd build
          make -j$(nproc)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openmohaa-amd64-build
          path: build/
