# .github/workflows/build-openmohaa.yml
name: Build OpenMOHAA

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build for AMD64

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake libsdl2-dev libglew-dev libopenal-dev libvorbis-dev

      - name: Try build with Makefile (fallback if CMake not used)
        run: |
          if [ -f Makefile ]; then
            make -j$(nproc)
          elif [ -f CMakeLists.txt ]; then
            mkdir build
            cd build
            cmake ..
            make -j$(nproc)
          else
            echo "No Makefile or CMakeLists.txt found." >&2
            exit 1
          fi

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: openmohaa-amd64-build
          path: |
            build/
            *.bin
            *.so
            openmohaa*
