name: Build OpenMOHAA No Release

on:
  push:
    paths:
      - ".github/workflows/build-openmohaa-no-release.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build OpenMOHAA for amd64

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone OpenMOHAA
        run: git clone --recursive https://github.com/openmoh/openmohaa.git src

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            clang \
            lld \
            flex \
            bison \
            libsdl2-dev \
            libopenal-dev \
            libcurl4-openssl-dev

      - name: Configure CMake
        run: cmake -S src -B .cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=.cmake/install

      - name: Build
        run: cmake --build .cmake --parallel

      - name: Install
        run: cmake --install .cmake

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: openmohaa-amd64
          path: .cmake/install/
