name: Build Xash3D FWGS Bots

# 🔒 Required for publishing releases
permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    # Trigger only if workflow file changes
    paths:
      - '.github/workflows/build-xash3d-fwgs-bots.yml'
    # Also trigger for major commits
    branches:
      - bot10

jobs:
  filter-major-commits:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      run_build: ${{ steps.check_message.outputs.run_build }}
    steps:
      - name: Check for major commit
        id: check_message
        run: |
          git fetch --depth=2
          msg="$(git log -1 --pretty=%B)"
          echo "Commit message: $msg"
          if [[ "$msg" =~ (MAJOR|BREAKING|feat!\:) ]]; then
            echo "run_build=true" >> "$GITHUB_OUTPUT"
          else
            echo "run_build=false" >> "$GITHUB_OUTPUT"
          fi

  build-and-release:
    name: Build bot10 and publish release
    needs: filter-major-commits
    if: github.event_name == 'workflow_dispatch' || needs.filter-major-commits.outputs.run_build == 'true'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout bot10 branch
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential gcc-multilib g++-multilib libsdl2-dev

    - name: Configure CMake
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -B build -S .

    - name: Build shared libs
      run: |
        cmake --build build -- -j$(nproc)

    - name: Prepare release directory
      run: |
        mkdir -p release
        find build -name '*.so' -exec cp {} release/ \;

    - name: Set release tag
      run: echo "RELEASE_TAG=xash3d-fwgs-bots-$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        name: Xash3D FWGS Bots
        files: release/*.so
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
