name: Build & Package OpenMoHAA

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            pkg-config \
            libsdl2-dev \
            libopenal-dev \
            libogg-dev \
            libvorbis-dev \
            libjpeg-dev \
            zlib1g-dev

      - name: Configure & compile
        run: |
          echo "Workspace root: $GITHUB_WORKSPACE"
          # Clean out any old build dir
          rm -rf build
          mkdir build
          # -S = source dir, -B = build dir
          cmake -S "$GITHUB_WORKSPACE" -B build
          cmake --build build -- -j$(nproc)

      - name: Assemble dist folder
        run: |
          rm -rf dist
          mkdir -p dist
          # copy the exact files you need from build
          cp build/cgame.x86_64.so            dist/
          cp build/game.x86_64.so             dist/
          cp build/launch_openmohaa_base.x86_64       dist/
          cp build/launch_openmohaa_breakthrough.x86_64 dist/
          cp build/launch_openmohaa_spearhead.x86_64  dist/
          # libraries may be in build/lib or installed system‑wide
          cp build/libopenal.so.1   dist/ 2>/dev/null || true
          cp build/libSDL2-2.0.so.0 dist/ 2>/dev/null || true
          cp build/omohaaded.x86_64 dist/
          cp build/openmohaa.x86_64 dist/

      - name: Upload full package artifact
        uses: actions/upload-artifact@v4
        with:
          name: openmohaa-full-package
          path: dist/
