name: Build Bot10 AMD64 and Release

on:
  push:
    branches:
      - bot10
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build bot10 and publish release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout bot10 branch
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential gcc-multilib g++-multilib libsdl2-dev

    - name: Configure CMake
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -B build -S .

    - name: Build shared libs
      run: |
        cmake --build build -- -j$(nproc)

    - name: Prepare release directory
      run: |
        mkdir -p release
        find build -name '*.so' -exec cp {} release/ \;

    - name: Set release tag
      run: |
        echo "RELEASE_TAG=xash3d-fwgs-bots-$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        name: Xash3D FWGS Bots
        files: release/*.so
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
