# .github/workflows/build-openmohaa.yml
name: Build OpenMOHAA

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build OpenMOHAA for amd64

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            clang \
            lld \
            flex \
            bison \
            libsdl2-dev \
            libopenal-dev \
            libcurl4-openssl-dev
        working-directory: ${{ github.workspace }}

      - name: Configure CMake
        run: cmake -B .cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./.cmake/install
        working-directory: ${{ github.workspace }}

      - name: Build
        run: cmake --build .cmake --parallel
        working-directory: ${{ github.workspace }}

      - name: Install
        run: cmake --install .cmake
        working-directory: ${{ github.workspace }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openmohaa-amd64
          path: .cmake/install/
